name: UNIT TESTS
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install dependencies
        run: uv sync --all-groups
      - name: Run Tests
        run: uv run pytest tests/

  static_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install dependencies
        run: uv sync --all-groups
      - name: Run MyPy
        run: uv run mypy src/ --ignore-missing-imports
      - name: Run Flake8
        run: uv run flake8 src/ --max-line-length 100
      - name: Run Pyflakes
        run: uv run pyflakes src/
      - name: Run PyCodeStyle
        run: uv run pycodestyle src/ --max-line-length 100
      - name: Run Pylint
        run: uv run pylint src/
      - name: Run Bandit
        run: uv run bandit -r src/ -c ./pyproject.toml
    needs:
      - test