name: Docker Deployment
on:
    workflow_dispatch:

jobs:
  deploy:
      if: github.ref_name == 'main' && github.ref_type == 'branch'
      runs-on: ubuntu-latest
      steps:
        - name: Setup QEMU
          uses: docker/setup-qemu-action@v3
        - name: Setup Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to Docker
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_API_KEY }}
        - name: Build and Push
          uses: docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: ${{secrets.DOCKER_USER }}/fb-stats-worker:latest
            platforms: linux/arm64
